### ISSUE TITLE
Not really understand Super Important Notes

### ISSUE THREAD

**Issue by whj768702** [Eliav2/how-react-hooks-work#3]
hi Eliav2,  Thank you for the article. I read your article and feel a little confused. The order of the demos seems to be reversed. Did I misunderstand? 

![image](https://user-images.githubusercontent.com/15810101/131963028-4f3d6316-2877-4e4f-a946-fcc065a66962.png)

**Comment by Eliav2** [comment]
can you further explain what made you feel confused?

**Comment by whj768702** [comment]
The first one says to call the state hook in effect, but the example does not call it in effect. The example that pops up when you click on it is updateCycle. I understand it should be RenderCycle. Can you help me to explain? Thank you very much.

**Comment by Eliav2** [comment]
yes you are right! this was a mistake and I fixed it now, thank you
